# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_to_image.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'text_to_image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13text_to_image.proto\"m\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\r\n\x05steps\x18\x04 \x01(\x05\x12\x10\n\x08guidance\x18\x05 \x01(\x02\x12\r\n\x05\x64type\x18\x06 \x01(\t\"F\n\rImageResponse\x12\x14\n\x0c\x62\x61se64_image\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2=\n\x0bTextToImage\x12.\n\rGenerateImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_to_image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=23
  _globals['_IMAGEREQUEST']._serialized_end=132
  _globals['_IMAGERESPONSE']._serialized_start=134
  _globals['_IMAGERESPONSE']._serialized_end=204
  _globals['_TEXTTOIMAGE']._serialized_start=206
  _globals['_TEXTTOIMAGE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
